### PR TITLE
Build consistent EVSE id and uid at all level.

### PR DESCRIPTION
**Pull request by jerome-benoit**
It's a breaking change that should not be merged until the uid change are
sorted out with Gireve.

OICP code must port the id and uid generation fix made here.

Signed-off-by: Jérôme Benoit <jerome.benoit@sap.com>

### CODE REVIEW

**Comment by jerome-benoit** [comment]
> It's a breaking change that should not be merged until the uid change are
> sorted out with Gireve.

You've merged it ... I assume you have a test plan with Gireve.

**Comment by LucasBrazi06** [comment]
> You've merged it ... I assume you have a test plan with Gireve.

To be reviewed and no draft PR means you tested it.

**Comment by jerome-benoit** [comment]
> > You've merged it ... I assume you have a test plan with Gireve.
> 
> To be reviewed and no draft PR means you tested it.

We can't test OCPI until it's deployed on QA. So, no real tests have been done, only the unit tests that are not really relevant regarding OCPI. 

I've just not changed to way UID are build but connector ID have changed the impact need to be assessed in QA before.

**Comment by LucasBrazi06** [comment]
> I've just not changed to way UID are build but connector ID have changed the impact need to be assessed in QA before.

Ok, thanks Jerome, let's proceed like you described then.
I'll try to deploy to our QA system and I wait for your green light.

**Pull request merged**
